name: streamlit-demo
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.6
  - streamlit
  - tqdm
  - pandas
  - altair
  - pip
  - pip:
     - -e .  # install git checkout of streamlit-demo in editable mode
     - pydriller
  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
